FEATURE(oioswift): Introduce `openio_bind_virtual_address_fqdn`
 ##### SUMMARY

To avoid the redefinition of `openio_oioswift_filter_s3token` and `openio_oioswift_filter_authtoken` when the endpoint isn't a IP address but a FQDN.

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION

```
        openio_oioswift_filter_s3token:
          use: "egg:swift3#s3token"
          delay_auth_decision: "True"
          auth_uri: "http://my.fqdn.net:35357"

        openio_oioswift_filter_authtoken:
          paste.filter_factory: keystonemiddleware.auth_token:filter_factory
          auth_type: password
          auth_url: "http://my.fqdn.net:35357"
          www_authenticate_uri: "http://my.fqdn.net:5000"
          insecure: "True"
          region_name: "{{ openio_s3_region }}"
          project_domain_id: default
          user_domain_id: default
          project_name: service
          username: swift
          password: "{{ openio_keystone_swift_password }}"
          delay_auth_decision: "True"
          include_service_catalog: "False"
          memcached_servers: "{{ groups['keystone'] \
            | map('extract', hostvars, ['openio_bind_address'])\
            | map('regex_replace', '$', ':6019') \
            | list | unique | join(',') }}"
          cache: swift.cache
          token_cache_time: 300
          revocation_cache_time: 60
          memcache_security_strategy: ENCRYPT
          memcache_secret_key: memcache_secret_key
```